// Supabase数据库初始化脚本
// 在浏览器控制台中运行此脚本来初始化数据库表

const SUPABASE_URL = 'https://xjjzgxqrxddbqsdcqeqa.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqamFneGFxcnhkZGJxc2RjcWVxYSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzM0MDcwODkwLCJleHAiOjIwNDk2NDY4OTB9.sG5pP6Lq8o8e2wQ2aWq2pN8lY3vj7qC9rM1b4vZ6y5m';

// 创建表的SQL
const CREATE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS express_compensation_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number text NOT NULL,
    amount numeric(10,2) NOT NULL,
    record_type text NOT NULL CHECK (record_type IN ('compensation', 'advance')),
    is_paid boolean NOT NULL DEFAULT false,
    record_date date NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_express_compensation_records_date ON express_compensation_records(record_date);
CREATE INDEX IF NOT EXISTS idx_express_compensation_records_type ON express_compensation_records(record_type);
CREATE INDEX IF NOT EXISTS idx_express_compensation_records_paid ON express_compensation_records(is_paid);

-- 启用RLS
ALTER TABLE express_compensation_records ENABLE ROW LEVEL SECURITY;

-- 创建RLS策略（允许所有操作）
DROP POLICY IF EXISTS "Users can view all records" ON express_compensation_records;
CREATE POLICY "Users can view all records" ON express_compensation_records FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert records" ON express_compensation_records;
CREATE POLICY "Users can insert records" ON express_compensation_records FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update records" ON express_compensation_records;
CREATE POLICY "Users can update records" ON express_compensation_records FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Users can delete records" ON express_compensation_records;
CREATE POLICY "Users can delete records" ON express_compensation_records FOR DELETE USING (true);
`;

// 尝试创建表
async function initializeDatabase() {
    try {
        console.log('开始初始化Supabase数据库...');
        
        // 检查表是否存在
        const checkResponse = await fetch(`${SUPABASE_URL}/rest/v1/express_compensation_records?limit=1`, {
            method: 'GET',
            headers: {
                'apikey': SUPABASE_ANON_KEY,
                'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
                'Content-Type': 'application/json'
            }
        });
        
        if (checkResponse.ok) {
            console.log('✅ 数据库表已存在');
            return true;
        } else if (checkResponse.status === 404) {
            console.log('⚠️ 数据库表不存在，请手动在Supabase SQL Editor中执行以下SQL:');
            console.log(CREATE_TABLE_SQL);
            return false;
        } else {
            console.error('❌ 检查数据库表时出错:', checkResponse.status, await checkResponse.text());
            return false;
        }
    } catch (error) {
        console.error('❌ 初始化数据库失败:', error);
        return false;
    }
}

// 运行初始化
initializeDatabase().then(result => {
    if (result) {
        console.log('🎉 数据库初始化成功！');
    } else {
        console.log('💡 请在Supabase SQL Editor中运行上述SQL脚本，然后刷新页面重试。');
    }
});